# รูปแบบ "Myth-Busting ทางการแพทย์" 120 วินาที

สูตรของผู้ใช้ (ที่มา: ไฟล์ `script-structure-myth-busting-120s.md` ที่ผู้ใช้ส่งมา 8 ต.ค. 2026) สำหรับคลิปแอนิเมชัน 2D การ์ตูนช่อง 2 นาที 16:9 ซับไทย เล่าเป็นบทสนทนาคนไข้–หมอ ใช้ได้กับทุกหัวข้อ "ความเชื่อผิด → หลักฐาน" ในขั้น 3 (เขียนบท) และขั้น 7 (ประกอบ MP4)

เลือกรูปแบบนี้เมื่อผู้ใช้พูดว่า myth-busting, คำเชื่อผิด, ตำนาน vs ความจริง, คนไข้ถามหมอตอบ หรือถามว่ามีสูตรเดิมไหม ถ้าผู้ใช้ไม่ระบุ ให้ถามว่าจะใช้รูปแบบนี้หรือเขียนบทแบบอิสระ

> **ตัวอย่างหัวข้อในสูตร (น้ำเต้าหู้/ถั่วเหลืองกับมะเร็งเต้านม) และงานวิจัยที่ผู้ใช้อ้าง ยังไม่ได้ตรวจกับ PubMed ในรอบที่เพิ่มรูปแบบนี้** ห้ามคัดตัวเลขหรือข้อความตัวอย่างไปใช้เป็นข้อเท็จจริง ต้องทำขั้น 2 และตรวจ abstract ใหม่ทุกครั้ง ไฟล์ในโฟลเดอร์ `assets/templates/` ใช้ข้อความ placeholder ล้วน ไม่มีข้อมูลสุขภาพ

## 1. หลักการ

1. เปิดด้วยความเชื่อผิดที่คนคุ้นหู แล้วค่อยเฉลย ไม่เปิดด้วยความรู้
2. เล่าผ่านบทสนทนาคนไข้–หมอ ให้ผู้ชมรู้สึกว่าเป็นคนถามเอง
3. ตอบข้อกังวลก่อน อธิบายกลไกทีหลัง
4. ใช้ภาพเปรียบเทียบอธิบายกลไกอย่างน้อย 1 ภาพ (กราฟแท่ง, ตัวรับ)
5. ตัวเลขจากงานวิจัยจริง มีผู้แต่ง วารสาร ปี
6. จบด้วยสิ่งที่ทำได้จริง แล้วค่อยชวนแชร์
7. หนึ่งฉาก = หนึ่งแนวคิด

## 2. ตารางเวลา (ปรับแต่ละช่วงได้ ±3 วินาที รวมต้อง 120 วินาที ฉากกลไกยาวที่สุด)

| # | เวลา | ช่วง | หน้าที่ | ภาพหลัก | ซับ |
|---|---|---|---|---|---|
| 1 | 0–5 | Hook | ขึ้นความเชื่อผิดตัวใหญ่ | สิ่งของในความเชื่อ + `?` + ป้าย "คำเชื่อผิด" | 1 บรรทัด |
| 2 | 5–17 | Question | คนไข้ถามภาษาพูด (≤15 วินาที, 45–55 คำ) | คนไข้ + หมอ | 3 บรรทัดสั้น |
| 3 | 17–31 | Reassure + ศัพท์ | หมอคลายกังวล แนะนำศัพท์ 1–2 คำ | หมอชี้นิ้ว + `≠` | 3 บรรทัด |
| 4 | 31–45 | Mechanism 1 | เปรียบเทียบขนาด/ฤทธิ์ | กราฟแท่งสูง–เตี้ย + แว่นขยาย | 2 บรรทัด |
| 5 | 45–65 | Mechanism 2 | กลไกในร่างกาย 3 จังหวะ | ตัวรับ + ตัวละครสารเข้าจับ | 3 บรรทัด |
| 6 | 65–85 | Evidence | งานวิจัย 3 ชิ้น | การ์ดเลื่อนเข้าทีละใบ | 3 บรรทัด |
| 7 | 85–97 | Practical | ควรกิน/ควรเลี่ยง | ✓ ไม่เกิน 3, ✗ 1–2 | 2 บรรทัด |
| 8 | 97–105 | Fact Card | สรุป 4 บรรทัด | การ์ดขาว หัวเขียว + ตัวละครยกนิ้ว | 1 บรรทัด |
| 9 | 105–114 | CTA | ชวนแชร์ + เปิดให้ถาม | ตัวละครทั้งสองยกแก้วชน | 2 บรรทัด |
| 10 | 114–120 | Logo | ปิดแบรนด์ ไม่มีเสียงพูด เสียงกระดิ่งสั้น ๆ | โลโก้ + วงแหวนวาด + ประกายดาว เฟดขาวตอนท้าย | ไม่มี |

## 3. บทตามช่วง (แม่แบบและกฎ)

**1 Hook** `[กินหรือทำสิ่งที่คนกังวล] บ่อย ๆ ระวัง[ผลเสียที่คนกลัว] เพราะ[เหตุผลที่ฟังดูมีเหตุผล]?` ลงท้าย `?` เสมอ และต้องมีป้าย "คำเชื่อผิด" กำกับ ตัวอย่างจากผู้ใช้: "กินน้ำเต้าหู้บ่อย ๆ ระวังเนื้องอกโต เพราะมีฮอร์โมนเพศหญิงเยอะ?"

**2 Question** `หมอคะ [คนใกล้ตัว] บอกว่า[ความเชื่อ] [เหตุผลที่ได้ยินมา] จริงไหมคะ?` ภาษาพูด ไม่ใช้ศัพท์แพทย์ อ้าง "เพื่อน/ญาติบอก" ทางเลือก: เปิดด้วยประโยคติดปาก เช่น "หมอคะ ไม่เจ็บเลย น่าจะไม่ใช่มะเร็งเนอะ?" **ข้อควรระวัง:** ห้ามใช้ประโยคติดปากแบบนี้ถ้าเนื้อหาจะกลายเป็นการบอกว่าอาการแบบนั้นปลอดภัย (ผิดกฎห้ามวินิจฉัยเฉพาะบุคคล)

**3 Reassure + ศัพท์** 3 ประโยค: (1) คลายกังวล "ไม่ต้อง[อด/กลัว/เลิก]ของโปรดครับ" (2) รับรองส่วนที่จริง "[สาร] มี[ศัพท์]จริง" (3) แยกให้ชัด "แต่ไม่ใช่[สิ่งที่เข้าใจผิด]" ยอมรับส่วนจริงก่อนเสมอ ศัพท์ใหม่ไม่เกิน 1–2 คำ มีคำอธิบายสั้น ๆ บนจอ **ข้อควรระวัง:** "ไม่ต้องอด" พูดได้เมื่อหลักฐานในตารางขั้น 2 รองรับจริงเท่านั้น ถ้าหลักฐานผสมหรือไม่พอ ให้ปรับเป็น "ยังไม่มีหลักฐานว่า…"

**4 Mechanism 1** `ฤทธิ์ของมัน[อ่อน/น้อย]กว่า[สิ่งที่คนกลัว] เป็น[ตัวเลขเชิงเปรียบเทียบ]` ใช้ภาพสูง vs เตี้ย "ร้อย ๆ เท่า" เป็นภาพรวม ไม่ใช่ตัวเลขที่อ้างว่าวัดได้ และต้องมีหลักฐานรองรับ

**5 Mechanism 2** 3 จังหวะ: เกริ่นภาพเปรียบเทียบ → ทำอะไร (แย่ง/จับ/เกาะ) → ผลลัพธ์ ใช้คำว่า "ได้ยากขึ้น" ไม่ใช่ "ไม่ได้เลย" แอนิเมชันตรงกับคำพูดทีละจังหวะ

**6 Evidence** การ์ดละ 4 บรรทัด: `[ประชากร/จำนวน]` / `[สถานที่ / ระยะติดตาม]` / `[ผลลัพธ์ตัวเลขเดียว]` / `[ผู้แต่ง et al. วารสาร ปี]` 1 การ์ด = 1 ตัวเลข เรียงจากตรงประเด็นที่สุดไปภาพรวม ถ้าเป็นงานเชิงสังเกตต้องมีบรรทัด "งานวิจัยเชิงสังเกต แสดงความสัมพันธ์ ไม่ใช่การพิสูจน์เหตุและผล" ตรวจตัวเลขทุกตัวกับ abstract ใน PubMed

**7 Practical** `เลือก[แบบธรรมชาติ/ปลอดภัย] เช่น [3 ตัวอย่าง] ยกเว้น [สิ่งที่ควรเลี่ยง]` ✓ ≤3, ✗ ≤1–2 ข้อควรเลี่ยงต้องมีเหตุผลทางการแพทย์รองรับและแนะนำปรึกษาแพทย์

**8 Fact Card** 4 บรรทัด: ข้อเท็จจริงหลัก / กลไกสั้น ๆ / สิ่งที่งานวิจัยพบ / ข้อสรุปที่ทำได้จริง (เน้นเขียว)

**9 CTA** `สาย[กลุ่มคน]สบายใจได้ แชร์คลิปนี้ไป[ช่วยล้างความเข้าใจผิด]กันครับ` + "สงสัยตรงไหน คอมเมนต์ถามได้เลย" (สูตรเดิมใช้ "ถามหมอ" ให้เลี่ยง: ตัวละครไม่ใช่แพทย์จริง และห้ามตอบวินิจฉัยเฉพาะบุคคลในคอมเมนต์) แล้วปิดด้วย disclaimer "ข้อมูลเพื่อความรู้ทั่วไป ไม่ใช่การวินิจฉัยหรือการรักษา โปรดปรึกษาแพทย์ผู้ดูแล" (กฎของ skill: ต้องมีเสมอ)

**10 Logo** ไม่มีเสียงพูด

## 4. ภาษาและความถูกต้อง (บังคับ ซ้อนกับกฎของ skill)

- ทุกตัวเลขมีแหล่งใน PubMed พร้อม DOI
- งานเชิงสังเกต → "สัมพันธ์กับ…", "พบว่าคนที่…มีความเสี่ยงต่ำกว่า"; งานทดลองสุ่ม → "ช่วยลด…" ห้าม "ป้องกันได้/รักษาหาย/ไม่มีวันเป็น" กับงานเชิงสังเกต
- กลไกใช้ "ได้ยากขึ้น" · แยกอาหารปกติออกจากอาหารเสริมสกัดเสมอ · ระบุขอบเขตประชากร · ผู้ป่วยระหว่างรักษาให้ปรึกษาแพทย์ก่อนปรับอาหาร

## 5. ซับไตเติล (กฎของรูปแบบ → สิ่งที่ pipeline ทำให้)

| กฎของสูตร | pipeline |
|---|---|
| ≤2 บรรทัด, ≤~45 ตัวอักษร/บรรทัด | 16:9 ได้ 2 บรรทัดตามความกว้างเฟรม ส่วน 9:16 ใช้ 3 บรรทัด (เฟรมแคบ) |
| อยู่บนจอ 2.5–7 วินาที/ซับ | เมื่อ storyboard มี `"format"` ระบบกันเวลาต่ำสุด 2.5 วินาทีต่อซับถ้าฉากยาวพอ และเตือนใน `warnings` ถ้าเกินช่วง 2.5–7 |
| พื้นหลังเข้มโปร่งแสง ตัวขาว | `"subtitle_box": true` |
| ฟอนต์ซับ Kanit Bold, ป้ายในฉาก Mali Bold | `"fonts": "kanit-mali"` (ทั้งคู่ Google Fonts SIL OFL อยู่ใน `assets/fonts/`; ค่าเริ่มต้นยังเป็น Sarabun) |
| คนไข้ม่วงอ่อน หมอขาว | `"speaker": "patient"` / `"doctor"` ต่อฉาก (ซับม่วงอ่อน/ขาว) |
| ขนาดซับ 50px บน 1080p | **ไม่ได้ทำตาม** pipeline ใช้ ~65px (0.060 ของความสูง) ให้อ่านง่ายบนมือถือ |
| ตัดคำตามความหมาย | ตัดด้วย PyThaiNLP (ตัดระหว่างคำ ไม่ตัดกลางคำ) |
| ศัพท์เทคนิคมีป้ายอธิบายบนจอ | overlay `label` ในฉากที่ 3 |

ห้ามใช้อักขระ ✓ ✗ ในข้อความ (Kanit/Mali/Sarabun ไม่มีกลิฟ จะเป็นสี่เหลี่ยม) ใช้ไอคอน `check` / `cross` แทน และเลี่ยง `•` (Mali แสดงเป็นเลขไทย ๑) ส่วน `≠ × ? % →` ใช้ได้

## 6. แปลงเป็น storyboard (ขั้น 7)

เริ่มจาก `assets/templates/myth-busting-120s.storyboard.json` (11 ฉาก: ช่วง Evidence แยกเป็น 3 ฉากเพราะการ์ดงานวิจัยกว้าง ต้องใหญ่พอให้ข้อความ 4 บรรทัดอ่านออกทั้ง 16:9 และ 9:16) แทนที่ `narration` ด้วยบทจริง ฉากละหนึ่งย่อหน้าตามที่ส่งเข้า TTS แล้วแทน placeholder ในการ์ด

| ช่วง | bg | layout | layers / overlays |
|---|---|---|---|
| Hook | warm | solo | prop ของในความเชื่อ + overlay "คำเชื่อผิด" (title) + `?` (number) |
| Question | sky | duo | ตัวละคร 2 ตัว (คนไข้ใส่ `coat`/`scrubs` สีอ่อน, หมอ `flip`) `speaker: patient` |
| Reassure | mint | trio | หมอ `point` + prop สองอย่างที่ "≠" + overlay ศัพท์ใหม่ |
| Mechanism 1 | lavender | duo | `bars` + `magnifier` |
| Mechanism 2 | clinic | split | ภาพเปรียบเทียบ (ปัจจุบัน `ring`+`drop`, `shield`+`cross`; ถ้าต้องการเซลล์/ตัวรับจริง ให้เพิ่ม prop ใน `props.py`) |
| Evidence ×3 | clinic | solo | prop `card` (`accent` น้ำเงิน) + overlay `label` size `s` 4 บรรทัดกลางการ์ด; ใบสุดท้ายเพิ่มหมายเหตุเชิงสังเกต |
| Practical | mint | quad | อาหาร 2 + `check` + `cross` พร้อมป้ายใต้ไอคอน |
| Fact Card | warm | solo | `card` (`accent` เขียว) + overlay 4 บรรทัด + ตัวละครยกนิ้วมุมขวาล่าง |
| CTA | sky | duo | ตัวละครสองตัว + `sparkle` + overlay disclaimer 2 บรรทัด |
| Logo | — | — | ไม่ใช่ฉาก: ใช้ `--logo-at end --logo-seconds 6` |

ตัวละครมีตัวเดียวคือ "น้องฟ้า" (เปลี่ยนสีเสื้อได้) ไม่มี prop "ถ้วย/แก้วชน" นอกจาก `mug`

```bash
R="uv run --with pycairo --with numpy --with pillow --with pythainlp python"
$R $S/make_video.py build --storyboard storyboard.json --voice voice/voiceover.wav \
   --parts-dir voice --group 4 --aspect 16:9 --logo ~/path/logo.png \
   --logo-at end --logo-seconds 6 --out out/ --name clip
```

ความยาวคลิป = เสียงพากย์จริง + 6 วินาทีโลโก้ ดังนั้นเขียนบทพูดให้ยาวราว 114 วินาที (ไม่ใช่ 120) ถ้าต้องการรวม 120 พอดี ถ้าไม่ส่ง `--logo` จะไม่มีช่วงโลโก้และคลิปสั้นลง 6 วินาที

## 7. ชุดคอนเทนต์ที่ได้จากสคริปต์เดียว

| ผลงาน | สถานะ |
|---|---|
| คลิป 120 วินาที 16:9 | ทำอัตโนมัติ (ขั้น 7) |
| แคปชันโพสต์ (สรุปทุกช่วง + ตัวเลข + อ้างอิง) และคอมเมนต์ปักหมุด | ให้โมเดลร่างเป็นข้อความจากตาราง REFERENCE MAP (ขั้น 3) |
| Carousel สไลด์ 1 (Hook ตัวใหญ่ + ป้ายคำเชื่อผิด), สไลด์ 2 (Fact Card), 3–4 (การ์ดงานวิจัย / ควรกิน-ควรเลี่ยง) | **ยังไม่ได้ทำอัตโนมัติ** ฉากที่เกี่ยวข้องมีใน storyboard แล้ว แต่ยังไม่มีคำสั่งส่งออกเป็นภาพนิ่งสะอาด ๆ |

## 8. เช็กลิสต์ก่อนส่งออก

- [ ] ตัวเลขทุกตัวตรงกับ abstract (ตรวจจาก PubMed ในรอบนี้ ไม่ใช่จากความจำ)
- [ ] ภาษาตรงชนิดงานวิจัย (สังเกต ≠ พิสูจน์) และมีหมายเหตุงานเชิงสังเกต
- [ ] แยกอาหารปกติกับอาหารเสริมแล้ว
- [ ] ซับไม่เกิน 2 บรรทัด (16:9) อ่านทันภายใน 2.5 วินาที ไม่มี warning ช่วงเวลาซับ
- [ ] มี disclaimer ท้ายคลิปและท้ายโพสต์
- [ ] ผู้ชมจบคลิปแล้วรู้ว่าต้องทำอะไรต่อ (ช่วง Practical) และไม่มีประโยคที่อ่านเป็นคำวินิจฉัยเฉพาะบุคคล

## 9. แม่แบบเปล่าสำหรับหัวข้อใหม่

```markdown
# หัวข้อ: [ความเชื่อผิดที่ต้องการแก้]
- กลุ่มเป้าหมาย: [...]   - ประเด็นหลัก (1 ประโยค): [...]
- ศัพท์ใหม่ (1–2 คำ): [...]   - ภาพเปรียบเทียบกลไก: [...]
## หลักฐาน (PubMed, ตรวจจริง)
1. [ผู้แต่ง ปี วารสาร] — ผลลัพธ์: [...] — DOI: [...] — ชนิด: [สังเกต/ทดลอง]
## บท: 0–5 Hook · 5–17 คนไข้ถาม · 17–31 หมอคลายกังวล+ศัพท์ · 31–45 เปรียบเทียบ · 45–65 กลไก ·
##     65–85 หลักฐาน 3 การ์ด · 85–97 ควรกิน/เลี่ยง · 97–105 Fact Card · 105–114 CTA · 114–120 Logo
```
